# Generated by Django 5.0.8 on 2024-08-24 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_movies_rating_avg_movies_rating_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movies",
            name="rating_last_updated",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
